#!/bin/sh

set -eu

case "${1:-}" in
	get)
		token="$(awk -F': ' '/oauth_token:/ { print $2; exit }' "$HOME/.config/gh/hosts.yml")"
		if [ -z "$token" ]; then
			exit 1
		fi
		printf 'username=x-access-token\n'
		printf 'password=%s\n' "$token"
		;;
	store|erase)
		;;
	*)
		exit 0
		;;
esac
